import json, sys
from datetime import datetime, timezone
def ts(s): return datetime.fromisoformat(s.replace('Z','+00:00'))
def check(task, snap, gen, now=None):
    by={i['sku']:i for i in snap['items']}; out=[]
    now = now or datetime.now(timezone.utc)
    gen_at = ts(gen['generated_at'])
    out.append(('count', len(gen['items'])==task['deliverable_spec']['item_count']))
    out.append(('length', len(gen['text'])<=task['deliverable_spec']['max_chars']))
    # SKU<->URL binding: each item's url must be the snapshot url of the SAME sku
    out.append(('source', all(i['sku'] in by and by[i['sku']]['url']==i['url'] for i in gen['items'])))
    out.append(('price', all(by.get(i['sku']) and by[i['sku']]['price_new']==i['price'] for i in gen['items'])))
    out.append(('currency', all(i['currency']==snap['items'][0]['currency'] for i in gen['items']) if gen['items'] else False))
    # freshness window is two-sided: data seen no earlier than 24h before generation, and not in the future
    out.append(('freshness', all(0 <= (gen_at-ts(by[i['sku']]['seen_at_utc'])).total_seconds()<=86400 for i in gen['items'] if i['sku'] in by)))
    # deadline: generated by deadline, not before snapshot existed, and not in the future
    out.append(('deadline', gen_at<=ts(task['deadline_utc']) and gen_at>=ts(snap['taken_at_utc']) and gen_at<=now))
    out.append(('amount', gen['amount']==task['amount']))
    skus=[i['sku'] for i in gen['items']]
    out.append(('dedupe_version', len(skus)==len(set(skus)) and gen['generator_version']==task['deliverable_spec']['generator_version']))
    return out
if __name__=='__main__':
    t=json.load(open(sys.argv[1])); s=json.load(open(sys.argv[2])); g=json.load(open(sys.argv[3]))
    r=check(t,s,g); print('\n'.join(f"{'PASS' if v else 'FAIL'} {k}" for k,v in r)); print('DECISION', 'CAPTURE' if all(v for _,v in r) else 'VOID')
